package dosecord.core.ports

import java.time.Instant
import java.util.UUID

/** The `medications.status` CHECK values. Medication-level pause is schedule-driven (a `Paused` revision, ADR-004); the
  * status mirrors it for list views.
  */
enum MedicationStatus(val dbValue: String):
  case Active extends MedicationStatus("active")
  case Paused extends MedicationStatus("paused")
  case Archived extends MedicationStatus("archived")

object MedicationStatus:
  def fromDbValue(value: String): MedicationStatus =
    values.find(_.dbValue == value).getOrElse(throw new IllegalArgumentException(s"unknown medication status '$value'"))

/** What a create writes into `medications`. `name_norm` is generated by the database (`lower(btrim(name))`).
  */
final case class NewMedication(
    id: UUID,
    accountId: UUID,
    name: String,
    doseAmount: Option[BigDecimal] = None,
    doseUnit: Option[String] = None,
    instructions: Option[String] = None
)

final case class StoredMedication(
    id: UUID,
    accountId: UUID,
    name: String,
    nameNorm: String,
    doseAmount: Option[BigDecimal],
    doseUnit: Option[String],
    instructions: Option[String],
    status: MedicationStatus,
    createdAt: Instant
)

/** `medications` (R11/R18): one medication per `(user_id, name_norm)` while not archived — enforced by
  * `uq_medication_name`, surfaced here as a find for the wizard's find-or-create (M1.9).
  */
trait MedicationRepository:
  def insert(row: NewMedication, now: Instant): Unit
  def get(id: UUID): Option[StoredMedication]

  /** The not-archived medication of the account with this normalised name (`lower(btrim(...))` applied by the caller),
    * for the re-add-offers-update path of M1.9 (R18).
    */
  def findByNameNorm(accountId: UUID, nameNorm: String): Option[StoredMedication]
