package dosecord.core.domain

import dosecord.contracts.HhMm
import dosecord.contracts.Weekday

import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId
import java.time.zone.ZoneOffsetTransition

import scala.jdk.CollectionConverters.*

/** Golden fixtures and rows for `Evaluator.occurrences` over the seven M0.7 zones (ROADMAP M1.2). Per zone: a
  * multi-slot-group week (Mon-Fri 08:00 and 21:30, Sat-Sun 10:00) and every tzdb transition in 2025-01-01..
  * 2029-01-01 (or the last four recorded transitions for zones without one in that window) exercised with wall times
  * around the transition clock. Rows are generated by the evaluator; each row's `(scheduledFor, dstKind)` is
  * re-verified against `Dst.resolveLocal`, which the M0.7 DST goldens pin independently.
  */
object OccurrenceGolden:

  final case class Fixture(name: String, revision: ScheduleRevision, from: Instant, to: Instant):
    def key: String = s"${revision.zone.getId}|$name"

  final case class Row(fixtureKey: String, localDate: LocalDate, slotKey: String, dstKind: DstKind, scheduledFor: Instant):
    def render: String = s"$fixtureKey|$localDate|$slotKey|${dstKind.dbValue}|$scheduledFor"

  object Row:
    def parse(line: String): Row =
      line.split("\\|", -1) match
        case Array(zone, name, localDate, slotKey, kind, instant) =>
          Row(
            s"$zone|$name",
            LocalDate.parse(localDate),
            slotKey,
            DstKind
              .fromDbValue(kind)
              .getOrElse(throw IllegalArgumentException(s"unknown dst_kind: $kind")),
            Instant.parse(instant)
          )
        case _ => throw IllegalArgumentException(s"malformed golden row: $line")

  val ResourcePath = "core/test/resources/occurrence-golden.txt"

  private val WeekRule: Rule = Rule.FixedTimes(
    List(
      SlotGroup(
        List(Weekday.Mon, Weekday.Tue, Weekday.Wed, Weekday.Thu, Weekday.Fri),
        List(HhMm.unsafe("08:00"), HhMm.unsafe("21:30"))
      ),
      SlotGroup(List(Weekday.Sat, Weekday.Sun), List(HhMm.unsafe("10:00")))
    )
  )

  private val TransitionRule: Rule = Rule.FixedTimes(
    List(
      SlotGroup(
        Weekday.values.toList,
        List("00:30", "02:15", "02:30", "03:30", "12:00", "23:45").map(HhMm.unsafe)
      )
    )
  )

  private val TransitionWindowStart = Instant.parse("2025-01-01T00:00:00Z")
  private val TransitionWindowEnd = Instant.parse("2029-01-01T00:00:00Z")
  private val TransitionMargin = Duration.ofHours(48)

  private def transitions(zone: ZoneId): List[ZoneOffsetTransition] =
    val rules = zone.getRules
    // Same enumeration as DstGolden: recurring-rule transitions only appear via nextTransition.
    val recent = Iterator
      .unfold(TransitionWindowStart)(instant =>
        Option(rules.nextTransition(instant))
          .filter(_.getInstant.isBefore(TransitionWindowEnd))
          .map(t => (t, t.getInstant))
      )
      .toList
    if recent.nonEmpty then recent else rules.getTransitions.asScala.takeRight(4).toList

  private def weekFixture(zone: ZoneId): Fixture =
    Fixture(
      "week",
      ScheduleRevision(WeekRule, zone),
      Instant.parse("2026-06-15T00:00:00Z"), // a Monday
      Instant.parse("2026-06-22T00:00:00Z")
    )

  private def transitionFixture(zone: ZoneId, transition: ZoneOffsetTransition): Fixture =
    Fixture(
      s"transition:${transition.getInstant}",
      ScheduleRevision(TransitionRule, zone),
      transition.getInstant.minus(TransitionMargin),
      transition.getInstant.plus(TransitionMargin)
    )

  def fixtures: List[Fixture] =
    for
      zone <- DstGolden.Zones
      fixture <- weekFixture(zone) +: transitions(zone).map(transitionFixture(zone, _))
    yield fixture

  def rows: List[Row] =
    for
      fixture <- fixtures
      candidate <- Evaluator.occurrences(fixture.revision, fixture.from, fixture.to)
    yield Row(fixture.key, candidate.localDate, candidate.slotKey, candidate.dstKind, candidate.scheduledFor)

  def content: String =
    val header = List(
      "# Evaluator.occurrences golden rows over the seven M0.7 zones; do not hand-edit",
      s"# tzdb=${TzdbVersion.runtimeVersion()} zones=${DstGolden.Zones.map(_.getId).mkString(",")}",
      s"# regenerate: ./mill core.test.runMain dosecord.core.domain.occurrenceGoldenGenerate $ResourcePath"
    )
    (header ++ rows.map(_.render)).mkString("", "\n", "\n")
end OccurrenceGolden
